# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
permalink: /blog/:year/:month/:day/:title/
relative_permalinks: false
encoding: utf-8

# Setup
title:               Agostinho Brito
#tagline:             'foo's website
description:         Blog pessoal de Agostinho Brito
#
url: "http://agostinhobritojr.github.io"
# url: ""
baseurl: ""
urlimg: "/images/"
markdown: kramdown
kramdown:
  math_engine: mathjax

paginate: 5
paginate_path: "/blog/page:num"
excerpt_separator: <!--more-->
default_bg: sitebg.jpg
default_logo: sitelogo.png
safe: false
#timezone:    America/Chicago
future:      true


## code highlight options
syntax_highlighter: rouge
input: GFM

gems:
  - github-pages
  - font-awesome-sass
  - jekyll-redirect-from
  - jekyll-mentions

jekyll-mentions:
  base_url: https://twitter.com

include: [".htaccess", "tutorial", "apps"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "rakefile", "README.md", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "LICENSE", "vendor", "assets", "_plugins", "public/dormant"]

# About/contact
author:
  name:              Agostinho Brito
  url:               http://agostinhobritojr.github.io
  avatar:         foo.png
  #email:           

# Owner/author information
owner:
  name:           Agostinho Brito
  avatar:         foo.png
  #email:          
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:
  # Social networking links used in footer. Update and remove as you like.
  twitter:        agostinhobritojr
#  facebook:       ajuste.tecnico.75
  github:         agostinhobritojr
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:
  tumblr:  
  google_plus:    https://plus.google.com/+agostinhobrito
  # orcid and google scholar IDs are different than standard username.
  orcid: 0000-0002-2054-2339
  gscholar: agostinhobritojr

## sidebar links:
# For external links add external: true
links:
  - title: <i class="iconside iconm-home"></i> Home
    url: /
  - title: <i class="iconside iconm-user"></i> About
    url: /about/
  - title: <i class="fa fa-graduation-cap"></i> Cursos
    url: /cursos/
  - title: <i class="fa fa-leanpub"></i> Tutoriais
    url: /tutoriais/

# Google Custom Search:
google_search:  013706804520974097595:xx1la6swmkw

# Twitter stream widget:
# Replace xyz123abc with your twitter widget id from https://twitter.com/settings/widgets
twitter_widget_id: agostinhobritoj

# Add disqus username for Disqus comment board:
disqus_shortname: agostinhobritojr

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-41839650-1

## END ##



